<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625212518 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE refresh_tokens ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_refresh_tokens_refresh_token RENAME TO UNIQ_9BACE7E1C74F2195');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE refresh_tokens ALTER id SET DEFAULT nextval(\'refresh_tokens_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_9bace7e1c74f2195 RENAME TO uniq_refresh_tokens_refresh_token');
    }
}
